---
deployment:
  tasks:
    - stage: compile 
      script: 
        - npm i
    - stage: deploy
      script: 
        - npm run build
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp dist $DEPLOYPATH