export const LOGIN = {
  REQUEST: "@@AUTH/LOGIN/REQUEST",
};

export const PROFILE = {
  REQUEST: "@@AUTH/PROFILE/REQUEST",
};

export const LOGOUT = {
  REQUEST: "@@AUTH/LOGOUT/REQUEST",
  SUCCESS: "@@AUTH/LOGOUT/SUCCESS",
};
